#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <time.h>

#define EMIT_COMMENT(str) printf("## " str "\n");
#define EMIT_CONSTANT_INT(name) printf("compileTime constant " #name " := %d.\n", (int)name)
#define EMIT_CONSTANT_HEX_INT(name) printf("compileTime constant " #name " := 16r%08x.\n", (int)name)

int main()
{
    EMIT_COMMENT("fcntl.h");
    EMIT_CONSTANT_HEX_INT(O_RDONLY);
    EMIT_CONSTANT_HEX_INT(O_WRONLY);
    EMIT_CONSTANT_HEX_INT(O_RDWR);
    EMIT_CONSTANT_HEX_INT(O_CREAT);
    EMIT_CONSTANT_HEX_INT(O_EXCL);
    EMIT_CONSTANT_HEX_INT(O_NOCTTY);
    EMIT_CONSTANT_HEX_INT(O_TRUNC);
    EMIT_CONSTANT_HEX_INT(O_APPEND);
    EMIT_CONSTANT_HEX_INT(O_NONBLOCK);
    EMIT_CONSTANT_HEX_INT(O_NDELAY);
    EMIT_CONSTANT_HEX_INT(O_SYNC);
    EMIT_CONSTANT_HEX_INT(O_FSYNC);
    EMIT_CONSTANT_HEX_INT(O_ASYNC);
    EMIT_CONSTANT_HEX_INT(O_DIRECTORY);
    EMIT_CONSTANT_HEX_INT(O_NOFOLLOW);
    EMIT_CONSTANT_HEX_INT(O_CLOEXEC);
#ifdef O_LARGEFILE
    EMIT_CONSTANT_HEX_INT(O_LARGEFILE);
#endif
#ifdef O_DIRECT
    EMIT_CONSTANT_HEX_INT(O_DIRECT);
#endif
#ifdef O_NOATIME
    EMIT_CONSTANT_HEX_INT(O_NOATIME);
#endif
#ifdef O_PATH
    EMIT_CONSTANT_HEX_INT(O_PATH);
#endif
#ifdef O_DSYNC
    EMIT_CONSTANT_HEX_INT(O_DSYNC);
#endif
#ifdef O_TMPFILE
    EMIT_CONSTANT_HEX_INT(O_TMPFILE);
#endif

    EMIT_COMMENT("sys/mman.h")
    EMIT_CONSTANT_HEX_INT(PROT_NONE);
    EMIT_CONSTANT_HEX_INT(PROT_READ);
    EMIT_CONSTANT_HEX_INT(PROT_WRITE);
    EMIT_CONSTANT_HEX_INT(PROT_EXEC);
    EMIT_CONSTANT_HEX_INT(MAP_SHARED);
    EMIT_CONSTANT_HEX_INT(MAP_PRIVATE);
#ifdef MAP_32BIT
    EMIT_CONSTANT_HEX_INT(MAP_32BIT);
#endif
    EMIT_CONSTANT_HEX_INT(MAP_ANON);
    EMIT_CONSTANT_HEX_INT(MAP_ANONYMOUS);
#ifdef MAP_DENYWRITE
    EMIT_CONSTANT_HEX_INT(MAP_DENYWRITE);
#endif
#ifdef MAP_EXECUTABLE
    EMIT_CONSTANT_HEX_INT(MAP_EXECUTABLE);
#endif
    EMIT_CONSTANT_HEX_INT(MAP_FILE);
    EMIT_CONSTANT_HEX_INT(MAP_FIXED);
#ifdef MAP_GROWSDOWN
    EMIT_CONSTANT_HEX_INT(MAP_GROWSDOWN);
#endif
#ifdef MAP_HUGETLB
    EMIT_CONSTANT_HEX_INT(MAP_HUGETLB);
#endif
#ifdef MAP_LOCKED
    EMIT_CONSTANT_HEX_INT(MAP_LOCKED);
#endif
#ifdef MAP_NONBLOCK
    EMIT_CONSTANT_HEX_INT(MAP_NONBLOCK);
#endif
    EMIT_CONSTANT_HEX_INT(MAP_NORESERVE);
#ifdef MAP_POPULATE
    EMIT_CONSTANT_HEX_INT(MAP_POPULATE);
#endif
#ifdef MAP_STACK
    EMIT_CONSTANT_HEX_INT(MAP_STACK);
#endif
#ifdef MAP_SHARED_VALIDATE
    EMIT_CONSTANT_HEX_INT(MAP_SHARED_VALIDATE);
#endif
#ifdef MAP_SYNC
    EMIT_CONSTANT_HEX_INT(MAP_SYNC);
#endif
#ifdef MAP_HUGE_2MB
    EMIT_CONSTANT_HEX_INT(MAP_HUGE_2MB);
#endif
#ifdef MAP_HUGE_1GB
    EMIT_CONSTANT_HEX_INT(MAP_HUGE_1GB);
#endif
#ifdef MAP_UNINITIALIZED
    EMIT_CONSTANT_HEX_INT(MAP_UNINITIALIZED);
#endif

    EMIT_COMMENT("sys/socket.h");
    EMIT_CONSTANT_INT(SHUT_RD);
    EMIT_CONSTANT_INT(SHUT_WR);
    EMIT_CONSTANT_INT(SHUT_RDWR);

    EMIT_CONSTANT_INT(AF_UNIX);
    EMIT_CONSTANT_INT(AF_LOCAL);
    EMIT_CONSTANT_INT(AF_INET);
    EMIT_CONSTANT_INT(AF_INET6);
#ifdef AF_NETLINK
    EMIT_CONSTANT_INT(AF_NETLINK);
#endif
#ifdef AF_PACKET
    EMIT_CONSTANT_INT(AF_PACKET);
#endif

    EMIT_CONSTANT_INT(SOCK_STREAM);
    EMIT_CONSTANT_INT(SOCK_DGRAM);
    EMIT_CONSTANT_INT(SOCK_SEQPACKET);
    EMIT_CONSTANT_INT(SOCK_RAW);

    EMIT_CONSTANT_INT(SOL_SOCKET);
    EMIT_CONSTANT_INT(SO_ACCEPTCONN);
#ifdef SO_ATTACH_FILTER
    EMIT_CONSTANT_INT(SO_ATTACH_FILTER);
#endif
#ifdef SO_ATTACH_REUSEPORT_CBPF
    EMIT_CONSTANT_INT(SO_ATTACH_REUSEPORT_CBPF);
#endif
#ifdef SO_ATTACH_REUSEPORT_EBPF
    EMIT_CONSTANT_INT(SO_ATTACH_REUSEPORT_EBPF);
#endif
#ifdef SO_BINDTODEVICE
    EMIT_CONSTANT_INT(SO_BINDTODEVICE);
#endif
    EMIT_CONSTANT_INT(SO_BROADCAST);
#ifdef SO_BSDCOMPAT
    EMIT_CONSTANT_INT(SO_BSDCOMPAT);
#endif
    EMIT_CONSTANT_INT(SO_DEBUG);
#ifdef SO_DETACH_FILTER
    EMIT_CONSTANT_INT(SO_DETACH_FILTER);
#endif
#ifdef SO_DOMAIN
    EMIT_CONSTANT_INT(SO_DOMAIN);
#endif
    EMIT_CONSTANT_INT(SO_ERROR);
    EMIT_CONSTANT_INT(SO_DONTROUTE);
#ifdef SO_INCOMING_CPU
    EMIT_CONSTANT_INT(SO_INCOMING_CPU);
#endif
    EMIT_CONSTANT_INT(SO_KEEPALIVE);
    EMIT_CONSTANT_INT(SO_LINGER);
#ifdef SO_MARK
    EMIT_CONSTANT_INT(SO_MARK);
#endif
    EMIT_CONSTANT_INT(SO_OOBINLINE);
#ifdef SO_PASSCRED
    EMIT_CONSTANT_INT(SO_PASSCRED);
#endif
#ifdef SO_PASSSEC
    EMIT_CONSTANT_INT(SO_PASSSEC);
#endif
#ifdef SO_PEEK_OFF
    EMIT_CONSTANT_INT(SO_PEEK_OFF);
#endif
#ifdef SO_PEERCRED
    EMIT_CONSTANT_INT(SO_PEERCRED);
#endif
#ifdef SO_PRIORITY
    EMIT_CONSTANT_INT(SO_PRIORITY);
#endif
#ifdef SO_PROTOCOL
    EMIT_CONSTANT_INT(SO_PROTOCOL);
#endif
    EMIT_CONSTANT_INT(SO_RCVBUF);
#ifdef SO_RCVBUFFORCE
    EMIT_CONSTANT_INT(SO_RCVBUFFORCE);
#endif
    EMIT_CONSTANT_INT(SO_RCVLOWAT);
    EMIT_CONSTANT_INT(SO_SNDLOWAT);
    EMIT_CONSTANT_INT(SO_RCVTIMEO);
    EMIT_CONSTANT_INT(SO_SNDTIMEO);
    EMIT_CONSTANT_INT(SO_REUSEADDR);
    EMIT_CONSTANT_INT(SO_REUSEPORT);
#ifdef SO_RXQ_OVFL
    EMIT_CONSTANT_INT(SO_RXQ_OVFL);
#endif
    EMIT_CONSTANT_INT(SO_SNDBUF);
#ifdef SO_SNDBUFFORCE
    EMIT_CONSTANT_INT(SO_SNDBUFFORCE);
#endif
    EMIT_CONSTANT_INT(SO_TIMESTAMP);
    EMIT_CONSTANT_INT(SO_TYPE);
#ifdef SO_BUSY_POLL
    EMIT_CONSTANT_INT(SO_BUSY_POLL);
#endif

    EMIT_CONSTANT_INT(IPPROTO_IP);
    EMIT_CONSTANT_INT(IPPROTO_UDP);
    EMIT_CONSTANT_INT(IPPROTO_TCP);
    EMIT_CONSTANT_INT(IPPROTO_IPV6);

    EMIT_CONSTANT_INT(CLOCK_REALTIME);
    EMIT_CONSTANT_INT(CLOCK_MONOTONIC);
    EMIT_CONSTANT_INT(CLOCK_PROCESS_CPUTIME_ID);
    EMIT_CONSTANT_INT(CLOCK_THREAD_CPUTIME_ID);
    return 0;
}
