"
I am a visitor for the AST nodes of the MoebiusBand AST nodes.
"
Class {
	#name : #MbndAstVisitor,
	#superclass : #Object,
	#category : #'MoebiusBandMetamodel-Core-AST'
}

{ #category : #visiting }
MbndAstVisitor >> visitBreakStatementNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitCasesOfCaseNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitCasesOfDefaultCaseNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitCasesOfNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitContinueStatementNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitDoWhileLoopNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitExpandedMessageSendNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitFunctionCallNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitIfConditionNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitLexicalScopeNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitLiteralValueNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitMessageChainMessageNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitMessageChainNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitPragmaNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitQuasiQuoteNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitQuasiUnquoteNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitQuoteNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitSequenceNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitSpliceNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitUnexpandedMessageSendNode: node [
]

{ #category : #visiting }
MbndAstVisitor >> visitWhileLoopNode: node [
]
