Class {
	#name : #MbndSlovimProgramEntitySSAValue,
	#superclass : #Object,
	#instVars : [
		'programEntity',
		'ssaValue'
	],
	#category : #'SysmelMoebiusCodeGenerator-Slovim-Module'
}

{ #category : #accessing }
MbndSlovimProgramEntitySSAValue >> programEntity [
	^ programEntity
]

{ #category : #accessing }
MbndSlovimProgramEntitySSAValue >> programEntity: anObject [
	programEntity := anObject
]

{ #category : #accessing }
MbndSlovimProgramEntitySSAValue >> ssaValue [
	^ ssaValue
]

{ #category : #accessing }
MbndSlovimProgramEntitySSAValue >> ssaValue: anObject [
	ssaValue := anObject
]
