SystemOrganization addCategory: #'Sysmel-Metamodel'!
SystemOrganization addCategory: 'Sysmel-Metamodel-APSG'!
SystemOrganization addCategory: 'Sysmel-Metamodel-Exceptions'!
SystemOrganization addCategory: 'Sysmel-Metamodel-MetaBuilders'!
SystemOrganization addCategory: 'Sysmel-Metamodel-MetaMethods'!
SystemOrganization addCategory: 'Sysmel-Metamodel-Program'!
SystemOrganization addCategory: 'Sysmel-Metamodel-Semantic'!
SystemOrganization addCategory: 'Sysmel-Metamodel-Types'!
