Class {
	#name : #MbndCompilerGeneratedMethod,
	#superclass : #MbndAbstractSpecificMethod,
	#category : #'SysmelMoebiusMetamodel-Core-Method'
}

{ #category : #testing }
MbndCompilerGeneratedMethod >> hasProgramEntityReflectiveNode [
	^ true
]

{ #category : #testing }
MbndCompilerGeneratedMethod >> isCompilerGeneratedMethod [
	^ true
]

{ #category : #testing }
MbndCompilerGeneratedMethod >> isDefinition [
	^ true
]

{ #category : #testing }
MbndCompilerGeneratedMethod >> isMessageMethod [
	^ true
]
