#include <stdio.h>
#include <sys/mman.h>
#ifdef linux
#include <linux/mman.h>
#endif

#define CONSTANT_INT(constName) \
    printf("alias %s := %d.\n", #constName, (int)constName);

int main()
{
    CONSTANT_INT(PROT_NONE);
    CONSTANT_INT(PROT_READ);
    CONSTANT_INT(PROT_WRITE);
    CONSTANT_INT(PROT_EXEC);

    CONSTANT_INT(MAP_SHARED);
    CONSTANT_INT(MAP_PRIVATE);
    CONSTANT_INT(MAP_32BIT);
    CONSTANT_INT(MAP_ANON);
    CONSTANT_INT(MAP_ANONYMOUS);
    CONSTANT_INT(MAP_DENYWRITE);
    CONSTANT_INT(MAP_EXECUTABLE);
    CONSTANT_INT(MAP_FILE);
    CONSTANT_INT(MAP_FIXED);
    CONSTANT_INT(MAP_GROWSDOWN);
    CONSTANT_INT(MAP_HUGETLB);
    CONSTANT_INT(MAP_LOCKED);
    CONSTANT_INT(MAP_NONBLOCK);
    CONSTANT_INT(MAP_NORESERVE);
    CONSTANT_INT(MAP_POPULATE);
    CONSTANT_INT(MAP_STACK);

#ifdef linux

    CONSTANT_INT(MAP_SHARED_VALIDATE);
    //CONSTANT_INT(MAP_FIXED_NOREPLACE);
    CONSTANT_INT(MAP_HUGE_2MB);
    CONSTANT_INT(MAP_HUGE_1GB);
    CONSTANT_INT(MAP_SYNC);
    CONSTANT_INT(MAP_UNINITIALIZED);
#endif

    return 0;
}
