name: Continuous integration
on: [push, pull_request]

jobs:
    build-unixes:
        name: Build Unixes
        runs-on: ${{ matrix.variant.os }}
        strategy:
            matrix:
                variant:
                    - os: ubuntu-18.04
                    - os: macos-latest
        env:
            LLC: llc-9
            CC: clang-9
            CXX: clang++-9
        steps:
            - uses: actions/checkout@v1

            - name: Image loading
              run: ./newImageForCI.sh

            - name: Package artifacts
              run: scripts/packageArtifacts.sh

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: build-artifacts
                  path: artifacts/dist

            - name: Run image tests
              continue-on-error: true
              run: scripts/runImageTests.sh

            - name: Run runtime libraries tests
              continue-on-error: true
              run: scripts/runRuntimeTests.sh

            - name: Upload test results
              continue-on-error: true
              uses: actions/upload-artifact@v1
              with:
                  name: test-results
                  path: artifacts/test-results
    build-windows:
        name: Build Windows
        runs-on: windows-2016
        steps:
            - uses: actions/checkout@v1

            - name: Image loading
              run: ./newImage.ps1

            - name: Package artifacts
              run: scripts/packageArtifacts.ps1

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: build-artifacts
                  path: artifacts/dist

            - name: Run image tests
              continue-on-error: true
              run: scripts/runImageTests.ps1

            - name: Upload test results
              continue-on-error: true
              uses: actions/upload-artifact@v1
              with:
                  name: test-results
                  path: artifacts/test-results
