name: Continuous integration
on: [push, pull_request]

jobs:
    build-unixes:
        name: Build Unixes
        runs-on: ${{ matrix.variant.os }}
        strategy:
            matrix:
                variant:
                    - os: ubuntu-18.04
                      llc: llc-9
                      platformName: linux64
                    - os: macos-latest
                      llc: llc
                      platformName: osx
        env:
            LLC: ${{ matrix.variant.llc }}
            PLATFORM_NAME: ${{ matrix.variant.platformName }}
            CC: clang
            CXX: clang++
        steps:
            - name: Install dependencies homebrew
              if: matrix.variant.os == 'macos-latest'
              run: brew install llvm

            - uses: actions/checkout@v1

            - name: Image loading
              run: ./newImageForCI.sh

            - name: Package artifacts
              run: scripts/packageArtifacts.sh

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: build-${{ env.PLATFORM_NAME }}
                  path: artifacts/dist/${{ env.PLATFORM_NAME }}

            - name: Run image tests
              continue-on-error: true
              run: scripts/runImageTests.sh

            - name: Run native runtime libraries tests
              continue-on-error: true
              run: scripts/runNativeRuntimeTests.sh

            - name: Run GC runtime libraries tests
              continue-on-error: true
              run: scripts/runGCRuntimeTests.sh

            - name: Upload test results
              continue-on-error: true
              uses: actions/upload-artifact@v1
              with:
                  name: test-results
                  path: artifacts/test-results
    build-windows:
        name: Build Windows
        runs-on: windows-latest
        env:
            PLATFORM_NAME: win64
        steps:
            - uses: actions/checkout@v1

            - name: Image loading
              run: ./newImage.ps1

            - name: Package artifacts
              run: scripts/packageArtifacts.ps1

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: build-${{ env.PLATFORM_NAME }}
                  path: artifacts/dist/${{ env.PLATFORM_NAME }}

            - name: Run image tests
              continue-on-error: true
              run: scripts/runImageTests.ps1

            - name: Upload test results
              continue-on-error: true
              uses: actions/upload-artifact@v1
              with:
                  name: test-results
                  path: artifacts/test-results
